/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: chyzhykov.roman (https://sketchfab.com/chijikoff.roma)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/aks-74u-pbs-74-6d2fdd8ea83c4b7fb89f1470f0260ae4
title: AKS-74U PBS/АКС-74У ПБС
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WeaponModel({ ...props }) {
  const group = useRef();
  const { position } = props;
  const { nodes, materials } = useGLTF('/weapon/weapon.gltf')
  return (
    <>
      <group position={position} scale={0.01} ref={group} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[2.46, 11.56, -51.89]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 10.64, -70.74]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_1.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 21.62, -184.71]} rotation={[0, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_2.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 21.62, -184.71]} rotation={[0, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_3.geometry} material={materials.AKS_Material} />
            </group>
            <group rotation={[0, -Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_4.geometry} material={materials.AKS_Material} />
            </group>
            <group rotation={[0, -Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_5.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[8.46, -11.23, 164.05]} rotation={[-0.59, -0.06, -3.13]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_6.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[-0.04, -40.45, 325.49]} rotation={[-1.58, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_7.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[-0.04, -40.45, 325.49]} rotation={[-1.58, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_8.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[-0.04, -40.45, 325.49]} rotation={[-1.58, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_9.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[-14.51, -12.94, 140.37]} rotation={[-1.58, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_10.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 17.66, 133.8]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_11.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -18.53, 69.34]} rotation={[0, -Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_12.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -30.32, 68.85]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_13.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 0, -2.13]} rotation={[0, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_14.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -37.27, 26.12]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_15.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -40.66, 24.68]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_16.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -21.17, -13.44]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_17.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -163.54, -64.01]} rotation={[-0.1, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_18.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -21.17, -13.44]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_19.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -37.81, 103.66]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_20.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[2.46, 11.56, -51.89]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_21.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[15.66, -4.66, 88.93]} rotation={[0, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_22.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 0, -2.13]} rotation={[0, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_23.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 10.64, -70.74]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_24.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 7.35, -81.03]} rotation={[Math.PI, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_25.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -1.47, -211.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_26.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 21.62, -184.71]} rotation={[0, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_27.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, 18.31, 29.49]} rotation={[0, Math.PI / 2, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_28.geometry} material={materials.AKS_Material} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_29.geometry} material={materials.AKS_Material} />
            </group>
            <group position={[0, -1.47, -207.63]} rotation={[Math.PI, 0, Math.PI]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_30.geometry} material={materials.AKS_pbs_material} />
            </group>
            <group position={[0, -1.47, -207.63]} rotation={[Math.PI, 0, Math.PI]} scale={100}>
              <mesh castShadow geometry={nodes.defaultMaterial_31.geometry} material={materials.AKS_pbs_material} />
            </group>
          </group>
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/scene.gltf')
