/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PiTabModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/pi-tablet/pi.gltf')
  return (
    <group scale={3} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.pCube2.geometry} material={materials.lambert9} position={[-0.02, 0, 0]} scale={[1, 0.42, 2.24]} />
      <mesh geometry={nodes.typeMesh1.geometry} material={materials.lambert9} position={[-0.58, 0.68, -0.12]} rotation={[-1.59, 0, 0]} scale={0.06} />
      <mesh geometry={nodes.typeMesh2.geometry} material={materials.lambert9} position={[0.53, 0.68, 0.1]} rotation={[-1.55, 0, Math.PI]} scale={0.06} />
      <mesh geometry={nodes.typeMesh3.geometry} material={materials.lambert9} position={[0.52, -0.68, -0.12]} rotation={[1.59, 0, -Math.PI]} scale={0.06} />
      <mesh geometry={nodes.typeMesh4.geometry} material={materials.lambert9} position={[-0.59, -0.68, 0.1]} rotation={[1.55, 0, 0]} scale={0.06} />
    </group>
  )
}

useGLTF.preload('/pi.gltf')
